backend:
  name: git-gateway
  branch: main
  base_url: https://desabafo25.netlify.app/

publish_mode: editorial_workflow

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "menu"
    label: "Menu del Locale"
    files:
      - file: "menu-data.json"
        label: "Dati del Menu"
        name: "menu_data_file" # Un nome interno univoco
        fields:
          - name: "menu_data"
            label: "Dati del menu"
            widget: "object"
            fields:
              - name: "categories"
                label: "Categorie"
                widget: "list"
                allow_add: true
                collapsed: false
                summary: "{{name}}"
                fields:
                  - name: "name"
                    label: "Nome Categoria"
                    widget: "string"
                    hint: "Es. 'Cocktail Classici'"
                  - name: "icon"
                    label: "Icona (Emoji)"
                    widget: "string"
                    required: false
                    hint: "Es. '🍸', '🍺', '☕'"
                  - name: "items"
                    label: "Articoli"
                    widget: "list"
                    collapsed: true
                    summary: "{{name}}"
                    fields:
                      - name: "name"
                        label: "Nome Articolo"
                        widget: "string"
                      - name: "description"
                        label: "Descrizione"
                        widget: "text"
                        required: false
                      - name: "price"
                        label: "Prezzo"
                        widget: "string"
                      - name: "available"
                        label: "Disponibile"
                        widget: "boolean"
                        default: true
